# Generated by Django 4.2.4 on 2024-03-16 19:10

from django.db import migrations, models
import django.utils.timezone
import learn_with_ease.web.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('likes', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('like', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_photo', models.ImageField(blank=True, null=True, upload_to='posts/', validators=[learn_with_ease.web.validators.image_size_validator])),
                ('cards', models.ManyToManyField(related_name='posts_data', to='flashcards.flashcards')),
                ('folders', models.ManyToManyField(related_name='posts_data', to='flashcards.folders')),
            ],
        ),
    ]
