# Generated by Django 4.2.4 on 2024-03-12 16:13

from django.db import migrations, models
import learn_with_ease.web.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlashCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True)),
                ('question_pictures', models.ImageField(blank=True, null=True, upload_to='flashcards/', validators=[learn_with_ease.web.validators.image_size_validator])),
                ('answer', models.TextField(blank=True, null=True)),
                ('answer_pictures', models.ImageField(blank=True, null=True, upload_to='flashcards/', validators=[learn_with_ease.web.validators.image_size_validator])),
                ('shuffle_question_and_answer', models.BooleanField(default=False)),
                ('only_show_answer', models.BooleanField(default=True)),
                ('type_answer', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Folders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=60)),
                ('archived', models.BooleanField(default=False)),
            ],
        ),
    ]
