# Generated by Django 4.2.4 on 2024-03-17 16:17

from django.db import migrations, models
import learn_with_ease.web.validators


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcards',
            name='answer',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='flashcards',
            name='answer_picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='flashcards/', validators=[learn_with_ease.web.validators.image_size_validator]),
        ),
        migrations.AlterField(
            model_name='flashcards',
            name='question',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='flashcards',
            name='question_picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='flashcards/', validators=[learn_with_ease.web.validators.image_size_validator]),
        ),
    ]
