# Generated by Django 4.2.4 on 2024-03-17 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_folders_folder_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcards',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='flashcards.folders'),
        ),
    ]
