# Generated by Django 4.2.4 on 2024-03-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0005_alter_flashcards_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='folders',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
