# Generated by Django 4.2.4 on 2024-03-23 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('flashcards', '0006_folders_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcards',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='posts.posts'),
        ),
        migrations.AddField(
            model_name='folders',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='posts.posts'),
        ),
    ]
