# Generated by Django 4.2.4 on 2024-03-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0007_flashcards_post_folders_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcards',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True),
        ),
        migrations.AlterField(
            model_name='folders',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True),
        ),
    ]
