# Generated by Django 4.2.4 on 2024-03-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0008_alter_flashcards_slug_alter_folders_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcards',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, default='none'),
        ),
        migrations.AlterField(
            model_name='folders',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, default='none'),
        ),
    ]
