# Generated by Django 4.2.4 on 2024-03-26 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_profiledata_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledata',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(120)]),
        ),
    ]
